"""Isolated resume authoring, research comparison, and ATS proxy domain."""

from .contracts import (
    ArtifactInput,
    AtsProxyEvaluation,
    ClaimOrigin,
    ComparisonManifest,
    ComparisonSlot,
    CriterionResult,
    EligibilityStatus,
    EvidenceSpan,
    EvidenceStatus,
    JobSnapshot,
    Requirement,
    RequirementGraph,
    RequirementKind,
    RequirementPriority,
    ResumeBoundaryError,
    ResumeClaim,
    ResumeConflictError,
    ResumeLabError,
    ResumeNotFoundError,
    ResumePurpose,
    ResumeRunStatus,
    RunItemStatus,
    StandardVersionInput,
    VariantKind,
)
from .requirements import (
    MAX_REQUIREMENTS,
    RequirementGraphLimitError,
    extract_requirement_graph,
    merge_requirement_clauses,
    requirement_graph_from_clauses,
)
from .artifacts import (
    ArtifactIntegrityError,
    ArtifactNamespace,
    ArtifactNotFoundError,
    ArtifactRepositoryError,
    ArtifactSecurityError,
    InvalidArtifactError,
    ManagedPdfWrite,
    ResumePdfArtifactRepository,
    VerifiedResumePdf,
)
from .fidelity import FidelityView, PdfFidelityReport, evaluate_pdf_fidelity
from .model import (
    LocalJsonResumeModel,
    LocalResumeModelConfig,
    ResumeModelError,
    ResumeNormalizationRequired,
    load_resume_model_config,
    model_artifact_sha256,
    resume_model_status,
)
from .runpod_model import (
    RUNPOD_API_ORIGIN,
    RUNPOD_MODEL_CONFIG_VERSION,
    RUNPOD_PROVIDER,
    RunpodReconciliationRequired,
    RunpodJsonResumeModel,
    RunpodResumeModelConfig,
    default_runpod_http_transport,
    runpod_resume_model_status,
)
from .pdf import PdfExtraction, PdfExtractionError, PypdfExtractor
from .scoring import score_ats_proxy
from .service import ResumeLabService
from .store import ResumeLabStore
from .tex import (
    CompiledPdf,
    RenderedResume,
    TectonicCompiler,
    TexPreflightReport,
    TexToolchainError,
    preflight_tex,
    render_resume_tex,
)
from .toolchain import (
    PdfFidelityError,
    ResumeArtifactBuild,
    ResumeArtifactToolchain,
)


__all__ = [
    "ArtifactInput",
    "ArtifactIntegrityError",
    "ArtifactNamespace",
    "ArtifactNotFoundError",
    "ArtifactRepositoryError",
    "ArtifactSecurityError",
    "AtsProxyEvaluation",
    "ClaimOrigin",
    "CompiledPdf",
    "ComparisonManifest",
    "ComparisonSlot",
    "CriterionResult",
    "EligibilityStatus",
    "EvidenceSpan",
    "EvidenceStatus",
    "FidelityView",
    "InvalidArtifactError",
    "JobSnapshot",
    "LocalJsonResumeModel",
    "LocalResumeModelConfig",
    "MAX_REQUIREMENTS",
    "RequirementGraphLimitError",
    "ManagedPdfWrite",
    "PdfExtraction",
    "PdfExtractionError",
    "PdfFidelityError",
    "PdfFidelityReport",
    "PypdfExtractor",
    "RenderedResume",
    "Requirement",
    "RequirementGraph",
    "RequirementKind",
    "RequirementPriority",
    "ResumeBoundaryError",
    "ResumeClaim",
    "ResumeConflictError",
    "ResumeLabError",
    "ResumeLabService",
    "ResumeLabStore",
    "ResumeModelError",
    "ResumeNormalizationRequired",
    "ResumeNotFoundError",
    "ResumePurpose",
    "ResumeRunStatus",
    "RunItemStatus",
    "RUNPOD_API_ORIGIN",
    "RUNPOD_MODEL_CONFIG_VERSION",
    "RUNPOD_PROVIDER",
    "RunpodReconciliationRequired",
    "RunpodJsonResumeModel",
    "RunpodResumeModelConfig",
    "StandardVersionInput",
    "TectonicCompiler",
    "TexPreflightReport",
    "TexToolchainError",
    "VariantKind",
    "VerifiedResumePdf",
    "ResumeArtifactBuild",
    "ResumeArtifactToolchain",
    "ResumePdfArtifactRepository",
    "evaluate_pdf_fidelity",
    "extract_requirement_graph",
    "merge_requirement_clauses",
    "model_artifact_sha256",
    "load_resume_model_config",
    "preflight_tex",
    "render_resume_tex",
    "requirement_graph_from_clauses",
    "score_ats_proxy",
    "resume_model_status",
    "default_runpod_http_transport",
    "runpod_resume_model_status",
]
